GET http://localhost:3000/api/func


### Get BMI


POST http://localhost:3000/api/func HTTP/1.1
Content-Type: application/json

{
"weight_kg":90, 
"height_cm":183, 
"target_weight_kg":70, 
"time_frame_days":90
}